use_default_settings: true

server:
  secret_key: "change-me-to-a-random-string"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

redis:
  url: redis://redis:6379/0
